### PR TITLE
Updated README.md fixes

### PR DESCRIPTION
**Pull request by gbowne1**
This change includes fixes for the groups' global README.md file and ffixes the links to Shields.io Badges/Sheilds.

I fixed a few of the links to specific Shields.io badges/shields.

### CODE REVIEW

**Review by hitblast — CHANGES_REQUESTED** [review]
I guess you might need to change these:
Screenshot 2022-07-18 at 9 21 09 AM

To this:
`[About Me](https://github.com/taotnpwaft/metadata/blob/main/ABOUT.md)`

It's actually in reverse.

**Review by gbowne1 — COMMENTED** [review]
Still doesn't work.  Other than that, looks bood.

**Review by hitblast — COMMENTED** [review]
I guess there is a blank space between the `]` and the `(` which is why the hyperlink is ceasing to appear at all.

**Comment by gbowne1** [comment]
I saw that too.  

I did some reading about this on the Shields stuff.  At least for the github badges and shields.  It's a bit more complicated becasue each README.md will need to be updated per project.  

The GitHub Organization mode sheld/badge will show a total of all the Organization's projects stars.  You can still have individual project stars badges/shields.

**Review by hitblast — COMMENTED** [review]
Apparently we could just keep one small README.md for each project featuring the primary parts of it, and one large README.md containing all the literature stuff for our organization.

**Pull request merged**
